# Generated by Django 2.2.7 on 2019-11-25 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(70), django.core.validators.MinValueValidator(21)]),
        ),
    ]
