# Generated by Django 2.2.7 on 2019-11-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
    ]
