# Generated by Django 2.2.7 on 2019-11-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_remove_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='available',
            field=models.IntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
