# Generated by Django 2.2.7 on 2019-11-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_info_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='available',
            field=models.IntegerField(default=1),
        ),
    ]
