# Generated by Django 2.2.7 on 2019-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_auto_20191128_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
