# Generated by Django 2.2.6 on 2019-12-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20191201_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
