# Generated by Django 2.2.7 on 2019-12-04 10:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0007_auto_20191202_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
