# Generated by Django 2.2.7 on 2019-11-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20191125_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('label', models.CharField(max_length=1)),
                ('facet', models.CharField(max_length=20)),
                ('score', models.CharField(choices=[(1, '전혀 그렇지 않다.'), (2, '그렇지 않다.'), (3, '보통이다.'), (4, '약간 그렇다.'), (5, '매우 그렇다.')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
