# Generated by Django 2.2.7 on 2019-12-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigfive', '0003_auto_20191202_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='testname',
            field=models.IntegerField(null=True),
        ),
    ]
